.eslintrc.cjs, src/components/SegmentedControl/SegmentedControl.module.css, src/components/SegmentedControl/SegmentedControl.test.tsx, src/components/SegmentedControl/SegmentedControl.utils.ts, src/components/SegmentedControl/__snapshots__/SegmentedControl.test.tsx.snap
Segmented control can now correctly singularly disable options, it also renders the primary hierarchy correctly (vertical and disabled options were affected).
=> fix: segmented control disabled and vertical items

.github/dependabot.yml
storybook grouping did not include storybook package 😅
=> ci: fix storybook dependabot group

src/components/Button/__snapshots__/Button.test.tsx.snap, src/components/Card/__snapshots__/Card.test.tsx.snap, src/components/Divider/__snapshots__/Divider.test.tsx.snap, src/components/Menu/__snapshots__/Menu.test.tsx.snap, src/components/Table/__snapshots__/Table.test.tsx.snap, src/components/ThemeProvider/Ant.tsx, src/components/Typography/BodyX/__snapshots__/BodyX.test.tsx.snap, src/components/Typography/HX/__snapshots__/HX.test.tsx.snap, src/index.ts, src/test-utils.tsx
Exported testing utils to help wrap components with theme configuration in tests.
=> feat: export test utils

src/hooks/useFeedbackMessage/useFeedbackMessage.test.tsx, src/hooks/useFeedbackMessage/useFeedbackMessage.tsx, src/hooks/useFeedbackMessage/useFeedbackMessage.types.tsx
Updated the component to have the methods (`info`, `loading`, `success`, `warning`, `error`) to have return a Promise (of type `boolean`).
The issue has been notified in #331 .
=> fix: useFeedbackMessage methods returns a promise

src/components/Menu/Menu.module.css, src/components/Menu/Menu.tsx, src/components/Menu/__snapshots__/Menu.test.tsx.snap
Antd's popover menu is not generated correctly. The popover is generated on the left when the parent node has a smaller width than the popover content. In the case of the left sidebar, this causes an external output of the node. 
To fix this the specific case the CSS has been modified
=> fix: menu style on inline mode

src/components/Modal/Modal.module.css
We introduce some changes on height and width of modals, in both small and large sizes.
- Small modals will have width between 480 and 640 px (before: 600-800) and height between 480 and 640 px (before: 360-480);
- Large modals will take 55% of the viewport width (before: 75%) with limits between 720 and 1200 px (instead of 900-1600) and height of 50% viewport height, with limits between 540 and 1080 px (before: 85% and 540-1080 as limit).
=> fix: small and large modal width and height updated

src/components/Table/Table.Action.tsx, src/components/Table/Table.props.ts, src/components/Table/Table.test.tsx, src/components/Table/Table.types.ts
This PR aims to add React mouse event as parameter in Table actions onClick callback.
Actions onClick callback now receives React mouse event as last parameter.
=> feat(table): added React event as parameter in actions onClick callback

src/components/Modal/Modal.props.ts, src/components/Modal/Modal.tsx
This PR aims to proxy [Ant Design modal](https://ant.design/components/modal#api) properties `getContainer` and `destroyOnClose`.
Exposed `getContainer` and `destroyOnClose` properties.
=> feat(modal): expose getContainer and destroyOnClose props

jest.config.js, package.json, src/components/Table/Table.mocks.tsx, src/components/ThemeProvider/utils/themeToVariables.ts, src/themes/utils/generateTheme.ts, yarn.lock
The goal of this PR is to substitute Lodash per method packages ([officially deprecated](https://lodash.com/per-method-packages)) with `lodash-es`.
=> feat(pkg): switch to lodash-es from lodash per method packages

src/components/Button/Button.stories.tsx, src/components/Button/Button.tsx, src/components/Card/Card.stories.tsx, src/components/Card/Card.tsx, src/components/Divider/Divider.stories.tsx, src/components/Divider/Divider.tsx, src/components/Icon/Icon.stories.tsx, src/components/Icon/Icon.tsx, src/components/Menu/Menu.stories.tsx, src/components/Menu/Menu.tsx, src/components/Modal/Modal.stories.tsx, src/components/Modal/Modal.tsx, src/components/SegmentedControl/SegmentedControl.stories.tsx, src/components/SegmentedControl/SegmentedControl.tsx, src/components/Table/Table.stories.tsx, src/components/Table/Table.tsx, src/components/ThemeProvider/ThemeProvider.tsx, src/components/Typography/BodyX/BodyX.stories.tsx, src/components/Typography/BodyX/BodyX.tsx, src/components/Typography/HX/HX.stories.tsx, src/components/Typography/HX/HX.tsx
The goal of this PR is to remove function components `defaultProps` since they are deprecated as per [official RFC](https://github.com/reactjs/rfcs/blob/createlement-rfc/text/0000-create-element-changes.md)
Involved components are `Button`, `Card`, `Divider`, `Icon`, `Menu`, `Modal`, `SegmentedControl`, `Table`, `ThemeProvider`, `BodyX`, and `HX`.
=> feat: removed components defaultProps

package.json, src/hooks/useModal/useModal.test.tsx, src/hooks/useModal/useModal.tsx
Fixed a memorization problem on the useModal hook which caused modals to rerender whenever their content changed.
=> fix(modal): Fix useModal rerender issue on children change

src/components/Button/Button.props.ts, src/components/Button/Button.test.tsx, src/components/Button/Button.tsx
This PR aims at adding the `title` property to the Button component.
It's very useful for buttons that consist of only an icon and doesn't impact the style or the behaviour of the component.
=> feat(button): added title prop

src/components/Button/Button.module.css, src/components/Drawer/Drawer.Footer.tsx, src/components/Drawer/Drawer.Title.tsx, src/components/Drawer/Drawer.mocks.tsx, src/components/Drawer/Drawer.module.css, src/components/Drawer/Drawer.props.ts, src/components/Drawer/Drawer.stories.tsx, src/components/Drawer/Drawer.test.tsx, src/components/Drawer/Drawer.tsx, src/components/Drawer/Drawer.types.ts, src/components/Drawer/__snapshots__/Drawer.test.tsx.snap
This PR follows the [Drawer component introduction PR](https://github.com/mia-platform/design-system/pull/494) and introduces the following changes:
**New features:**
- Drawer footer can now be a custom node or can leverage standard properties (button, extra) for a predefined look.
- Drawer now has a closeIcon
- Drawer can now display a doc link
**Improvements:**
- Drawer types have been moved to a separate file
- Drawer stories and mocks have been refactored to be more meaningful and usable; Drawer stories now correctly show the drawer props in the Show Code tab
- Drawer styles are now imported from a CSS module
=> feat: drawer footer standard props and some improvements

package.json, src/components/Button/Button.props.ts, src/components/Button/Button.stories.tsx, src/components/Button/Button.test.tsx, src/components/Button/Button.tsx, src/components/Button/__snapshots__/Button.test.tsx.snap
This PR aims to add the `block` property to the button component. This property enables the button to fit the parent container witdh.
=> feat(button): Add block prop

src/components/Card/Card.module.css
Card padding style was only considering content and header, not skeleton.  
This caused skeleton to be 100% wide.  
This MR moves the left/right padding from just content and header to the card container itself
skeleton before:  
skeleton now:  
content before:
content now (unchanged):
- fixed skeleton padding
=> fix(card): fixed card padding for skeleton 

src/components/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap, src/components/Button/Button.stories.tsx, src/components/Icon/Icon.tsx, src/components/Icon/__snapshots__/Icon.test.tsx.snap, src/components/SegmentedControl/__snapshots__/SegmentedControl.test.tsx.snap
#357 suggests to have a different default for the [`Icon`](https://github.com/mia-platform/design-system/blob/main/src/components/Icon/Icon.tsx) prop, from the default value included in the theme to the [`currentColor` keyword](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#currentcolor_keyword).
I wasn't unsure if change the default on the Icon component (which will reflect to any usage of the `Icon` component) or to the `Icon` included in `Button` components (since it's more noticeable in buttons with _neutral_ hierarchy, see #521). I'm going with this implementation but I'm open for suggestions.
- `color` prop defaults to `currentColor`
- added in the Storybook the example _Neutral with icon_ to verify that the icon have its color changed during hover.
Closes #357
=> fix(Icon): color prop defaults to "currentColor"

src/components/Table/Table.mocks.tsx, src/components/Table/Table.module.css, src/components/Table/Table.props.ts, src/components/Table/Table.stories.tsx, src/components/Table/Table.test.tsx, src/components/Table/Table.tsx, src/components/Table/Table.types.ts, src/components/Table/__snapshots__/Table.test.tsx.snap
This PR adds the property `rowState` to the Table component. This property lets you specify the row's state (info, warning, error, success) based on the record. The state controls the background colour of the row.
- Added property `rowState`
Although in a limited manner, the PR addresses the issue https://github.com/mia-platform/design-system/issues/448
=> feat(Table): added rowState prop

package.json, src/components/Dropdown/Dropdown.stories.tsx, src/components/Dropdown/Dropdown.test.tsx, src/components/Dropdown/Dropdown.tsx, src/components/Dropdown/props.ts
I'm working on a component that needs to be aware of the changes of the nested `Dropdown` open status. Therefore, I added the according props in order to expose the needed state to the outer components.
I also need to modify the menu container to fix some positioning issues
- add `onOpenChange` prop, forwarded to the inner Antd component
- add `getPopupContainer` prop, forwarded to the inner Antd component
=> feat(Dropdown): add `onOpenChange` and `getPopupContainer` props

src/components/Dropdown/Dropdown.stories.tsx, src/components/Dropdown/Dropdown.test.tsx, src/components/Dropdown/Dropdown.tsx, src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap, src/components/Dropdown/dropdown.module.css, src/components/Dropdown/props.ts
This PR introduces:
- `Dropdown#initialSelectedItems` **optional** prop that helps selecting one or more items at first render.
- `Dropdown#multiple` **optional** prop that can be used to control whether dropdown highlights should consider multiple items or a single one.
**Screenshot below shows highlight in multiple mode**
=> feat(dropdown): highlight selected items with initialSelectedItems and multiple highlight support

src/components/Dropdown/Dropdown.stories.tsx, src/components/Dropdown/Dropdown.tsx, src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap, src/components/Dropdown/components/Label/__snapshots__/index.test.tsx.snap, src/components/Dropdown/components/Label/index.test.tsx, src/components/Dropdown/components/Label/index.tsx, src/components/Dropdown/dropdown.module.css, src/components/Dropdown/props.ts
Implements the tag support for the Dropdown menu items labels.
The tag will be shown at the end of the label.
The user can specify the tag as a Tag component, otherwise an error is thrown.
With `Dropdown.ItemLayout.Vertical`:
With `Dropdown.ItemLayout.Horizontal`:
#530
=> feat(Dropdown): add optional `Tag` at the end of menu items

package.json, src/components/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap, src/components/Button/Button.module.css, src/components/Button/Button.stories.tsx, src/components/Button/Button.tsx, src/components/Button/__snapshots__/Button.test.tsx.snap, src/components/Card/__snapshots__/Card.test.tsx.snap, src/components/Dropdown/Dropdown.test.tsx, src/components/Modal/__snapshots__/Modal.test.tsx.snap, src/components/Table/__snapshots__/Table.test.tsx.snap, yarn.lock
Remove extra padding from buttons with only icon.
I've also updated antd to v5.17 to leverage the new `Button#iconPosition` prop and remove our custom code
=> fix: remove extra padding from button with icon only

src/components/Modal/Modal.module.css
The update of the Ant Design library from version 5.13 to 5.17 in [this commit](https://github.com/mia-platform/design-system/commit/016533a47b8a97f6ac38f3fc10a6ba6ed669cf28#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L50) has secretly changed the implementation of the Ant modal by adding an extra wrapper around the ant-modal-content element. The CSS fix present here restores the correct functionality of the fullscreen modal.
=> fixed fullscreen modal regression with antd 5.13->5.17 update

src/components/Modal/Modal.module.css
The upgrade of the Ant Design library from version 5.13 to 5.17 in [this commit](https://github.com/mia-platform/design-system/commit/016533a47b8a97f6ac38f3fc10a6ba6ed669cf28#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L50) introduced a different version of `rc-dialog`, which places an additional wrapper around dialogs.
This wrapper does not have a specified height, preventing all children from adapting their height to previous ancestors.
The new element is inserted as the direct parent of our `.mia-platform-modal-content` node, so the new style introduced by this PR fixes the issue.
Closes #596
=> fix(modal): height issue due to antd version upgrade

src/components/Icon/Icon.tsx
Fixed returned type of Icon Component to be ReactElement
- Icon
=> fix: icon type as ReactElement

src/components/Modal/Modal.Body.tsx, src/components/Modal/Modal.mocks.tsx, src/components/Modal/Modal.module.css, src/components/Modal/Modal.stories.tsx, src/components/Modal/__snapshots__/Modal.test.tsx.snap
In case the lateral text (`aside.content`) contains a long text that needs scrolling, the title (`aside.title`) does not scroll with the rest of the container.
Also including a new Storybook test (_With Scrollable Aside_) to show the result.
[Screencast from 19-09-2024 16:44:49.webm](https://github.com/user-attachments/assets/ab30b779-1835-446e-9b6c-a9a1d61c2008)
Closes #597 
=> fix(Modal): fixed title in aside in case of scrollable content

src/components/Dropdown/Dropdown.stories.tsx, src/components/Dropdown/Dropdown.test.tsx, src/components/Dropdown/Dropdown.tsx, src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap, src/components/Dropdown/props.ts
Including new prop, called **selectable**, if not included it defaults to `true`. 
When set to `false`, any selection will not be saved. This might be useful in case a dropdown is used as a selection menu (and we do not need to show any previous selection when re-opening the menu).
Includes tests and storybook.
=> feat(Dropdown): including "selectable" prop, defaults to true

src/components/Dropdown/dropdown.module.css
recreate box-shadow for dropdown wrapper when the footer is appended
=> fix(dropdown): reset box-shadow when footer is appended

src/components/Dropdown/Dropdown.tsx
A classname starting with 0 is not a valid selector. Therefore, starting a class with a raw UUID may lead with a zero-lead class name.
The dropdown was already featuring a "unique classname" for the overlay so I've reworked things a little bit to provide more coherence.
=> fix(Dropdown): better classname to prevent class leading with 0 char

src/components/Dropdown/Dropdown.stories.tsx, src/components/Dropdown/Dropdown.tsx, src/components/Dropdown/dropdown.module.css, src/components/Dropdown/props.ts, src/themes/schema/shape.ts
The menu is now limited at 240px, height can be customized with `menuItemsMaxHeight` prop
Screenshots taken from the new stories where max height is set to `128px`
=> feat(Dropdown): menu max height controllable with `menuItemsMaxHeight` prop

src/components/Dropdown/dropdown.module.css
Removed instruction `width: fit-content` from class `mia-platform-dropdown-trigger` since it caused children to not be able to fill the parent width (CSS instruction has been removed altogether, `width` will be set to its default `auto`).
This instruction has been moved to the `dropdownRenderWrapper` CSS class to ensure that only the menu (when opened) will show items with the width of its content.
Here a quick video to show the result.
[Screencast from 21-10-2024 14:34:40.webm](https://github.com/user-attachments/assets/f5b902db-f5af-478a-b114-68e62ab0861d)
Unsure whether to create a new prop to handle this case. For now I'd stick with this behavior
Based on your changes, some of these checks may not apply. …
=> fix(Dropdown): `width: fit-content` attached to the menu instead of the dropdown

src/components/Switch/Switch.module.css, src/components/Switch/Switch.props.ts, src/components/Switch/Switch.stories.tsx, src/components/Switch/Switch.test.tsx, src/components/Switch/Switch.theme.ts, src/components/Switch/Switch.tsx, src/components/Switch/Switch.types.ts, src/components/Switch/__snapshots__/Switch.test.tsx.snap, src/components/Switch/index.ts, src/components/ThemeProvider/Ant.tsx, src/components/ThemeProvider/__tests__/__snapshots__/Ant.test.tsx.snap, src/index.ts
This PR introduces the **Switch** component. For now, it is a single component. Once we approve the development of component groups (discussion is in progress on issue #682), we will also create the SwitchGroup component.
=> feat(Switch): added Switch component

.storybook/preview.ts, .storybook/reset.css, src/components/Modal/Modal.module.css, src/components/Modal/Modal.stories.tsx
This PR introduces a fix on the Modal component regarding the height of the `aside` element.
The Storybook setup did not contain any CSS reset file; this means that the `box-sizing` property was implicitly set to `content-box` for certain elements. The `aside` element is an example of this: setting its height to 100% would result in it taking its container's height _plus_ its own vertical padding.
- updated aside element to have `box-sizing: border-box` and height set to 100%; 
- added CSS reset to storybook preview
- updated Modal stories to improve the ease of use
> **NOTE**  
> Some labels are used to generate release note entries: you can find the complete mapping between PR labels and release note …
=> fix(Modal): aside height calculated incorrectly

src/components/Button/Button.module.css
The goal of this PR is fixing a bug that displayed the `Button` icon not aligned with its label. 
> **NOTE**  
=> fix(Button): icon is centered and aligned with the label

src/components/Button/Button.module.css
Removed outline animation in the button if the type is `ghost` or `link`
Before fix
After fix
removed via css outline and box-shadow to the first div contained in the button that is added at button click
> **NOTE**  
Based on your changes, some of these checks may not apply. Please make sure to check …
=> fix(Button): removed outline and box shadow for ghost and link

src/components/Alert/Alert.module.css, src/components/Alert/Alert.test.tsx, src/components/Alert/Alert.tsx, src/components/Alert/__snapshots__/Alert.test.tsx.snap
=> Fix(Alert): Using phosphor icons in both default and compressed variants

src/components/Input/Input.stories.tsx, src/components/Input/Input.test.tsx, src/components/Input/Input.tsx, src/components/Input/InputAddon.tsx, src/components/Input/props.ts, src/utils/object.ts
The Input component now supports an object to be passed as a controlled value if the input has addons.
Additionally, you can specify custom prop names for the values in the addons by passing in their options a prop "name".
For the text input component, you can specify the prop valuePropName (defaults to "value") to customize the name of the value prop.
- The input now supports custom names to for the values of the input component and the addons
> **NOTE**  
For a more detailed overview of …
=> feat(Input): added custom names for input addon

package.json, src/components/Feedback/Feedback.module.css, src/components/Feedback/Feedback.tsx, src/components/Feedback/__snapshots__/Feedback.test.tsx.snap
This PR has the goal of setting the `Feedback` icon to a fixed dimension of 64x64px.
- updated icon size
> **NOTE**  
=> fix(Feedback): fixed icon size

src/components/Feedback/Feedback.module.css, src/components/Feedback/Feedback.props.ts, src/components/Feedback/Feedback.stories.tsx, src/components/Feedback/Feedback.test.tsx, src/components/Feedback/Feedback.tsx, src/components/Feedback/__snapshots__/Feedback.test.tsx.snap
This PR has the goal of using the newly created `Badge` component instead of a custom badge inside the `Feedback` component. Props, style, stories and tests have been updated accordingly.
IMPORTANT: these changes replace the `subtitle` prop of the custom badge with the `description` prop of the `Badge` component.
- updated props to include `BadgeProps`
- removed custom badge and replaced with `Badge` component
- removed useless style
> **NOTE**  
For a more detailed overview of PR labels, …
=> feat(Feedback): replaced custom badge with Badge component

src/components/Card/Card.module.css
This PR has the goal of fixing a bug in the Card component header, where a scrollbar was wrongly displayed in case of overflowing text or when a subtitle was added.  
Before:
After:
> **NOTE**  
Based on your changes, some of these checks may not apply. Please make sure to check the …
=> fix(Card): fixed overflow on header

src/components/Badge/Badge.module.css, src/components/Badge/Badge.tsx
This PR has the goal of removing tooltip style to prevent displaying errors.
- removed tooltip props from title and subtitle 
- removed style
> **NOTE**  
=> fix(Badge): removed tooltip style from Badge

src/components/Feedback/Feedback.tsx, src/components/Feedback/feedback.module.css
This PR has the goal of fixing a problem that was present when wrapping the `Feedback` component inside another component, such as `Modal`, where overflow was applied to content.
> **NOTE**  
Based on your changes, some of these checks may not apply. Please make sure to check the …
=> fix(Feedback): fixed style to prevent overflow errors

src/components/CardSelection/CardSelection.module.css, src/components/CardSelection/CardSelection.tsx, src/components/CardSelection/__snapshots__/CardSelection.test.tsx.snap
This PR has the goal of fixing the behavior of the `CardSelection` component icon when the `isHorizontal` prop is set to `true` to prevent it from shrinking with a long title text.
Before:
After:
> **NOTE**  
Based on your changes, some of these checks may not apply. Please make sure to …
=> fix(CardSelection): fixed horizontal icon displaying

src/components/Checkbox/checkbox.module.css
This PR has the goal of fixing a bug inside the  `Checkbox` component, which was visible when the checkbox contained text and was wrapped inside another component, such as `Input`. Now, the content is correctly centered and aligned.
Before:
After:
> **NOTE**  
Based on your changes, some …
=> fix(Checkbox): centered text content

src/components/Dropdown/components/Label/__snapshots__/index.test.tsx.snap, src/components/Feedback/__snapshots__/Feedback.test.tsx.snap, src/components/Select/select.module.css, src/components/Tag/Tag.module.css, src/components/Tag/Tag.props.ts, src/components/Tag/Tag.stories.tsx, src/components/Tag/Tag.test.tsx, src/components/Tag/Tag.tsx, src/components/Tag/__snapshots__/Tag.test.tsx.snap, src/components/Tag/types.ts
The colors reported on Figma have a fixed style, and the color can be specified using an enum.
- Tag:  The colors default colors can be passed as an enum in props
- Tag: Added "Chip" type. default is "Tag"
- Tag: Added the "icon" prop to specify a custom left icon for the Tag
> **NOTE**  
Based on your …
=> Feat(Tag): Added chip variant and fixed default colors styles

src/components/Table/Table.module.css, src/components/Table/Table.props.ts, src/components/Table/Table.stories.tsx, src/components/Table/Table.test.tsx, src/components/Table/Table.tsx, src/components/Table/__snapshots__/Table.test.tsx.snap
Added the prop `hasParentHeight` to `Table`: the prop adds the css property to `height:100%`on the table and its wrappers.
The property is useful in combination with the prop `scroll={{x: true, y: '100%'}}` to create unpaginated scrollable tables, without having to specify directly the height of the table as the y value of the object passed in the scroll prop. 
- Added hasParentHeight prop
> **NOTE**  
For a more detailed overview of PR labels, please refer to the [dedicated CONTRIBUTING …
=> fit parent height table

src/components/Input/Input.test.tsx, src/components/Input/Input.tsx, src/components/Input/props.ts, src/components/TextArea/TextArea.tsx, src/components/TextArea/props.ts
In this pull request, I'm adding the `onBlur` property to the `TextArea` and the `Input` components.
> **NOTE**  
=> feat(components): Add onBlur prop to Input and TextArea components

src/components/TextArea/TextArea.tsx
Fix autoSize behaviour in TextArea component: it didn't work because the prop was not passed to the BaseInput component
> **NOTE**  
=> Fix(TextArea): fix autoSize

src/components/Form/FormItem/FormItem.stories.tsx, src/components/Form/FormItem/FormItem.test.tsx, src/components/Form/FormItem/FormItem.tsx, src/components/Form/props.ts
If the FormItem is read-only, we added some default rendering for certain types of inputs.
Text inputs will render the input value; select and multiselect will render the labels associated with the input values separated by a comma.
-  added isReadOnly prop
> **NOTE**  
Based on your changes, some of …
=> feat: readonly form item render

package.json, src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap, src/components/SplitButton/SplitButton.test.tsx, src/components/SplitButton/SplitButton.tsx, src/components/SplitButton/props.ts
Exposed onOpenChange prop for the Split Button component without changing the internal logic
> **NOTE**  
=> feat(SplitButton): add onOpenChange prop

src/components/Badge/Badge.props.ts, src/components/Badge/Badge.stories.tsx, src/components/Badge/Badge.test.tsx, src/components/Badge/Badge.tsx, src/components/Badge/__snapshots__/Badge.test.tsx.snap
Added the prop hasMultilineDescription to Badge: by default the description is clipped and ellipsis is shown, but in some cases is desirable to have text falling back to the next line.
- Added prop hasMultilineDescription to Badge
> **NOTE**  
Based on your changes, some of these checks may not apply. …
=> Feat(Badge): Added hasMultilineDescription prop to badge

src/components/Dropdown/Dropdown.stories.tsx, src/components/Dropdown/Dropdown.test.tsx, src/components/Dropdown/Dropdown.tsx, src/components/Dropdown/components/Label/index.tsx, src/components/Dropdown/dropdown.module.css, src/components/Dropdown/props.ts
Added disabled prop to disable a dropdown item
- added disabled field to item prop
> **NOTE**  
=> enhancement(dropdown): added disabled prop for dropdown item

src/components/Form/FormItem/FormItem.test.tsx, src/components/Table/Table.props.ts, src/components/Table/Table.stories.tsx, src/components/Table/Table.tsx, src/components/Table/__snapshots__/Table.test.tsx.snap
This PR introduces a new flag for the Table component that prevents it from being remounted for `isLoading` prop change.
The remount is due to the Skeleton that is currently wrapping the table.
Removing the Skeleton altogether would be a breaking change and since there are many tables impacted I preferred not to risk and break anything.
We can make the breaking change later on.
> **NOTE**  
For a more detailed overview of PR labels, please refer to the [dedicated CONTRIBUTING …
=> feat(Table): prevent table remount on load

package.json, src/components/DatePickers/DatePicker/DatePicker.test.tsx, src/components/DatePickers/RangePicker/RangePicker.test.tsx, yarn.lock
DatePicker, RangePicker. Fixed tests
> **NOTE**  
=> chore(date-pickers): fix mock date in tests

src/components/Select/Select.stories.tsx, src/components/Select/Select.test.tsx, src/components/Select/Select.tsx, src/components/Select/props.ts
new prop maxTagCount & maxTagPlaceholder for select component
Added the ability to customize in multiple modes the number of tags the component can show
> **NOTE**  
=> added: new prop maxTagCount & maxTagPlaceholder for select component

src/components/Table/Table.props.ts
I changed the type of the onChange prop in the Table component
> **NOTE**  
=> fix(table): onChange prop type

src/components/Modal/Modal.props.ts, src/components/Modal/Modal.test.tsx, src/components/Modal/Modal.tsx
Added afterClose callback to intercept the modal closing. At the time the only way possible is using the onCloseClick callback, but this gets fired only on the x button press (not the backdrop click or the cancel button press).
> **NOTE**  
Based on your changes, some of these checks may not apply. …
=> feat(Modal): added modal onAfterClose prop

src/components/CardSelection/CardSelection.module.css, src/components/Form/Form.stories.tsx, src/components/Form/Form.test.tsx, src/components/Form/Form.tsx, src/components/Form/FormItem/FormItem.tsx, src/components/Form/props.ts
From this:
- <img width="301" alt="Screenshot 2025-03-20 alle 14 50 15" src="https://github.com/user-attachments/assets/7a6ad5ff-7b6d-4ef5-bc4a-9ecfa4e21ddc" />
To this:
-  <img width="306" alt="Screenshot 2025-03-20 alle 14 50 23" src="https://github.com/user-attachments/assets/74da7b19-7cfe-4a64-85ee-364a64d38998" />
- now it is possible to use FormInstance to handle form method
> **NOTE**  
For a more detailed overview of PR labels, please refer to the [dedicated CONTRIBUTING …
=> fixed: css cardSelection, feat: export Form.useForm

src/components/Checkbox/Checkbox.tsx, src/components/CheckboxGroup/__snapshots__/CheckboxGroup.test.tsx.snap, src/components/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap, src/components/RadioGroup/components/Radio/__snapshots__/index.test.tsx.snap, src/components/RadioGroup/components/Radio/index.tsx, src/components/Switch/Switch.tsx, src/components/Typography/BodyX/BodyX.types.ts
CHanged the color of descriptions inside components checkbox, radio and switch, using the new prop "hierarchy" with value "subtle"
> **NOTE**  
=> changed(): description color to checkbox, radio and switch

src/components/Select/Select.stories.tsx, src/components/Select/Select.test.tsx, src/components/Select/Select.tsx, src/components/Select/props.ts
In this PR, I add the support to the `optionRender` to possibly add some information in the dropdown. For example, a description which can help to choose the correct option.
> **NOTE**  
=> feat(Select): add optionRender props to select component

src/components/Input/Input.stories.tsx, src/components/Input/InputAddon.tsx, src/components/Select/Select.stories.tsx, src/components/Select/Select.tsx, src/components/Select/props.ts
In this PR, resolve issues when the popup content is longer than the width.
Also, resolves #763 using select virtualization by default.
Resolves #763
> **NOTE**  
=> feat(select): fix select virtualization, configuring popup width

src/components/Badge/Badge.props.ts, src/components/Badge/Badge.test.tsx, src/components/Badge/Badge.tsx, src/components/Badge/__snapshots__/Badge.test.tsx.snap
- icon prop accepts IconComponent and React.Node so that is possible to use a custom icon or image in the icon section of the Badge
Closes #1015 
> **NOTE**  
=> fix(badge): custom icon can be a react node

src/components/Dropdown/Dropdown.stories.tsx, src/components/Dropdown/Dropdown.test.tsx, src/components/Dropdown/Dropdown.tsx, src/components/Dropdown/props.ts
- Added prop `header` to add a custom header component to the dropdown. It contains two fields (`top`, and `bottom`) as the header can be placed both above and below the search input (when visible)
- Reset of search input when the dropdown is closed
> **NOTE**  
Based on your changes, some of these …
=> add dropdown header; reset search on dropdown close
