.storybook/addons/backgrounds.ts, .storybook/addons/theme.ts, .storybook/main.ts, .storybook/preview.ts, .storybook/theme.ts
Fixed Storybook base configurations
- backgrounds
- default components theme
- stories layout
- addons order
=> fix: storybook parameters, addons and theme configuration

jest.config.js, src/setupTests.ts
=> fix: added jest setup test file

src/components/ThemeProvider/Ant.tsx
Modified ant prefix class to mia-platform, fixed description typos
=> fix: ant prefix class, typos

src/components/Icon/Icon.tsx, src/utils/log.ts
Centralized a log error function
=> fix: log utils

.github/release.yml, .github/workflows/release.yml, .github/workflows/test.yml, package.json, src/components/Button/__snapshots__/Button.test.tsx.snap
Implement workflow for automatic release creation on tag
=> ci: release workflow

.github/pull_request_template.md, .storybook/addons/backgrounds.ts, .storybook/addons/docs.tsx, .storybook/addons/theme.ts, .storybook/decorators/theme.tsx, .storybook/main.ts, .storybook/manager.ts, .storybook/preview.ts, .storybook/theme.ts, src/components/Button/Button.module.css, src/components/Button/Button.stories.tsx, src/components/Button/Button.test.tsx, src/components/Button/Button.theme.ts, src/components/Button/Button.tsx, src/components/Button/Button.types.ts, src/components/Button/index.ts, src/components/Icon/Icon.stories.tsx, src/components/Icon/Icon.test.tsx, src/components/Icon/Icon.tsx, src/components/Icon/index.ts, src/components/ThemeProvider/Ant.tsx, src/components/ThemeProvider/ReactIcons.tsx, src/components/ThemeProvider/__tests__/Ant.test.tsx, src/components/ThemeProvider/__tests__/index.test.tsx, src/components/ThemeProvider/index.tsx, src/components/ThemeProvider/utils/__tests__/themeToVariables.test.ts, src/hooks/__tests__/index.test.tsx, src/setupTests.ts
Added missing licenses in all files
=> fix: added missing licenses

src/themes/schema/typography.ts
=> fix: font-style link

src/components/ThemeProvider/utils/__tests__/__snapshots__/themeDefaultStyle.test.ts.snap, src/components/ThemeProvider/utils/themeDefaultStyle.ts
Added height and width to theme default style
=> fix: theme default style

src/components/Button/Button.test.tsx, src/components/Button/Button.tsx, src/components/SegmentedControl/SegmentedControl.test.tsx, src/components/SegmentedControl/SegmentedControl.tsx
Added mouse event type to onClick, fixed tests 
Added mouse event parameter to onChange function
=> fix: segmented control pass event to onChange, fix button tests

src/components/Button/Button.stories.tsx, src/components/Button/Button.test.tsx, src/components/Button/Button.tsx, src/components/Button/Button.types.ts, src/components/Menu/Menu.mocks.tsx, src/components/Menu/Menu.stories.tsx, src/components/Menu/Menu.test.tsx, src/components/Menu/Menu.tsx, src/components/Menu/Menu.types.ts, src/components/Menu/Menu.utils.tsx, src/components/SegmentedControl/SegmentedControl.stories.tsx, src/components/SegmentedControl/SegmentedControl.test.tsx, src/components/SegmentedControl/SegmentedControl.tsx, src/components/SegmentedControl/SegmentedControl.types.ts, src/components/SegmentedControl/SegmentedControl.utils.ts, src/components/Typography/BodyX/BodyL/index.tsx, src/components/Typography/BodyX/BodyM/index.tsx, src/components/Typography/BodyX/BodyS/index.tsx, src/components/Typography/BodyX/BodyX.stories.tsx, src/components/Typography/BodyX/BodyX.tsx, src/components/Typography/BodyX/BodyX.types.ts
Aligned component types, added missing descriptions
=> Feat: Aligned component types

src/index.ts
Added missing menu component export
Added missing export
=> fix: exported menu component

src/components/Menu/Menu.theme.ts
Added missing properties in primary menu theme
Fixed primary theme
=> fix: primary menu theme

src/index.ts
Exported typography component
Added missing export
=> fix: exported typography component

.storybook/addons/docs.tsx
sort storybook controls alphabetically (required first)
sort storybook controls alphabetically (required first)
=> fix: sort storybook controls alphabetically (required first)

.github/workflows/test.yml
This PR removes the need for parallel builds (and coverall management of parallel build)
none a part my best intentions
=> ci: remove parallel builds

jest.config.js
Removed assets folder from coverage
=> fix: removed assets folders from test coverage

src/index.ts
Exported Table component
Exported component
=> fix: Table export

CONTRIBUTING.md, src/index.ts
Removed reference to CHANGELOG in CONTRIBUTING
=> fix: remove changelog reference in CONTRIBUTING

.github/pull_request_template.md
Added exported components check to pull requests template
=> fix: added exported components check to pull requests template

README.md
Fixed README.md description for local development
=> fix: updated README.md

src/components/Card/Card.module.css, src/components/Divider/Divider.props.ts, src/components/Icon/Icon.props.ts, src/components/Menu/Menu.props.ts, src/components/Menu/Menu.types.ts, src/components/SegmentedControl/SegmentedControl.props.ts, src/components/Table/Table.props.ts
- Corrected style and indentation of comments to props
- Removed useless CSS attributes from Card.module.css
=> fix: indentation & style

.github/release.yml
added refactor label matcher for release generation
=> ci: releaser refactor section

src/components/Modal/Modal.props.ts, src/components/Modal/Modal.tsx
solves #349 by adding isMaskClosable prop
=> feat(#349): modal isMaskClosable prop

src/components/Table/Table.Action.tsx, src/components/Table/Table.mocks.tsx, src/components/Table/Table.module.css, src/components/Table/Table.props.ts, src/components/Table/Table.stories.tsx, src/components/Table/Table.test.tsx, src/components/Table/Table.tsx, src/components/Table/Table.types.ts, src/components/Table/__snapshots__/Table.test.tsx.snap
Added actions columns to table component
Added edit and delete columns, and the ability to provide custom actions
[IDP-561](https://makeitapp.atlassian.net/jira/software/c/projects/IDP/boards/1220?selectedIssue=IDP-561)
=> feat(IDP-561): Table Actions Columns

src/components/ThemeProvider/utils/themeDefaultStyle.ts
=> fix: font dynamic import

src/components/Table/Table.test.tsx, src/components/Table/Table.tsx, src/components/Table/Table.types.ts
=> fix: table actions allows for action.onClick to control icon

src/components/Table/Table.stories.tsx, src/components/Table/Table.tsx, src/components/Table/Table.types.ts
=> fix: table action optional icon

src/components/Button/Button.module.css
Mini PR for removing unwanted box shadow from all buttons
=> fix: removed button box shadow

CONTRIBUTING.md, src/components/Tag/Tag.props.ts, src/components/Tag/Tag.stories.tsx, src/components/Tag/Tag.test.tsx, src/components/Tag/Tag.tsx, src/components/Tag/__snapshots__/Tag.test.tsx.snap, src/components/Tag/index.ts, src/index.ts
Added **Tag component** remapping only the fundamental props from the antd5 Tag.
=> feat(tag): added tag component

src/components/Breadcrumb/Breadcrumb.mocks.tsx, src/components/Breadcrumb/Breadcrumb.module.css
- Fixed scroll behaviour in dropdown when searchbar is visible
=> fix(Breadcrumb): fixed dropdown scroll

.eslintrc.cjs, src/components/Dropdown/Dropdown.stories.tsx, src/components/Dropdown/Dropdown.test.tsx, src/components/Dropdown/Dropdown.tsx, src/components/Dropdown/dropdown.module.css, src/components/Dropdown/props.ts, src/setupTests.ts
This PR introduces cascading options in the dropdown component
#530
=> feat(dropdown): cascading options

src/components/Breadcrumb/Breadcrumb.Collapsed.tsx, src/components/Breadcrumb/Breadcrumb.Dropdown.tsx
* Removed internal antd imports
Partially solves https://github.com/mia-platform/design-system/issues/588
=> fix(Breadcrumb): removed antd internal imports

src/components/Modal/Modal.module.css
Fix the button graphic issue in https://makeitapp.atlassian.net/browse/IDP-1783. For details, look ath the comment at https://github.com/mia-platform/design-system/commit/d7aaf57929e09535dcd5daeb7d90471bd9c76c28#commitcomment-146177733
=> fix(Modal): wrong css in modal footer-buttons

src/components/Button/Button.module.css
Fixes https://makeitapp.atlassian.net/browse/IDP-1880 / 1
=> Fix extra margin when a button have both icon and text

.github/pull_request_template.md, CONTRIBUTING.md
This PR specifies PR submission rules in the CONTRIBUTING file and improves the PR submission template
=> chore(contributing): add PR naming and labelling conventions

src/components/Button/Button.module.css
This PR fixes missing defaults in button css variables
=> fix(button): add css variable defaults to disabled state

src/components/Breadcrumb/Breadcrumb.Collapsed.tsx, src/components/Breadcrumb/Breadcrumb.Dropdown.tsx, src/components/Breadcrumb/Breadcrumb.Separator.tsx, src/components/Card/Card.tsx, src/components/Drawer/Drawer.Title.tsx, src/components/Drawer/Drawer.tsx, src/components/Icon/Icon.props.ts, src/components/Icon/Icon.test.tsx, src/components/Icon/Icon.tsx, src/components/Icon/__snapshots__/Icon.test.tsx.snap, src/components/Modal/Modal.Body.tsx, src/components/Modal/Modal.Title.tsx, src/components/Table/Table.tsx
The icon aria-labels have changes on each build because the applied component.name is changed by the minify process.  
- Icon
- Breadcrumb
- Card
- Drawer
- Modal
- Table
=> fix: allows custom aria-label and fixed icon aria-labels that are minified in the DS bundle

src/components/Button/Button.props.ts, src/components/Button/Button.stories.tsx, src/components/Button/Button.tsx
Added download prop to indicate the href attribute refers to a file to be downloaded rather than displayed in the browser
=> feat(Button): added download prop

src/components/Modal/Modal.module.css
Fixed scrollbar position: it is now outside the body instead of inside
Modal
=> fix(Modal): scrollbar position

src/components/Divider/Divider.props.ts, src/components/Divider/Divider.tsx, src/components/Dropdown/Dropdown.stories.tsx, src/components/Dropdown/Dropdown.test.tsx, src/components/Dropdown/Dropdown.tsx, src/components/Dropdown/components/Footer/index.module.css, src/components/Dropdown/components/Footer/index.test.tsx, src/components/Dropdown/components/Footer/index.tsx, src/components/Dropdown/dropdown.module.css, src/components/Dropdown/props.ts, src/themes/schema/spacing.ts
Added dropdown footer with customizable actions
#530 
=> feat(Dropdown): add footer with custom actions

src/components/Dropdown/Dropdown.stories.tsx, src/components/Dropdown/components/Label/index.test.tsx, src/components/Dropdown/components/Label/index.tsx, src/components/Dropdown/props.ts
Add icon support to dropdown menu items
<figure>
<figcaption>Horizontal layout</figcaption>
<br>
</figure>
<br>
<figure>
<figcaption>Vertical layout</figcaption>
<br>
</figure>
#530 
=> feat(dropdown): icon support for menu labels

src/components/BaseInput/BaseInput.tsx, src/components/BaseInput/__snapshots__/BaseInput.test.tsx.snap, src/components/Input/Input.test.tsx, src/components/Input/Input.tsx, src/components/InputNumber/InputNumber.stories.tsx, src/components/InputNumber/InputNumber.tsx, src/components/Search/Search.stories.tsx, src/components/Search/Search.test.tsx, src/components/Search/Search.tsx, src/components/Search/__snapshots__/Search.test.tsx.snap, src/components/Search/index.ts, src/components/Search/props.ts, src/index.ts
Added search input, minor fixes on base input and others.
=> feat(Search): Added Search input

src/components/Switch/Switch.module.css, src/components/Switch/Switch.theme.ts, src/components/Switch/Switch.tsx, src/components/ThemeProvider/__tests__/__snapshots__/Ant.test.tsx.snap
- handle shadow restored on enabled switch states
=> fix(Switch): adjusted handle shadow

src/components/RadioGroup/RadioGroup.stories.tsx, src/components/RadioGroup/components/Radio/index.module.css, src/components/RadioGroup/props.ts
=> fix(radio): storybook improvements

src/components/Switch/Switch.stories.tsx
The animation of the switch component was very clunky on storybook. This behaviour was caused by the storybook `actions` addon which was implicitly used to populate the `onChange` and `onClick` properties when they were not provided.
This PR fixes the issue by explicitly overwriting these props in the storybook.
=> fix(Switch): resolve Switch animation issues on storybook

.github/pull_request_template.md, CONTRIBUTING.md
- Updated PR template adding the map between PR labels and RN entries.
- Added label documentation in contributing
=> update(documentation): improved PR labelling documentation

.eslintrc.cjs, src/components/BaseInput/BaseInput.theme.ts, src/components/Input/Input.stories.tsx, src/components/Input/Input.test.tsx, src/components/Input/Input.tsx, src/components/Input/InputAddon.tsx, src/components/Input/__snapshots__/Input.test.tsx.snap, src/components/Input/input.module.css, src/components/Input/props.ts, src/components/Input/types.ts, src/components/Search/__snapshots__/Search.test.tsx.snap, src/components/Select/Select.tsx, src/components/Select/__snapshots__/Select.test.tsx.snap, src/components/Select/props.ts, src/components/ThemeProvider/Ant.tsx, src/components/ThemeProvider/__tests__/__snapshots__/Ant.test.tsx.snap
Implemented addons on text input (of type text, select and checkbox).
> **NOTE**  
=> Feat(Input): Implemented addons on text input

src/components/Select/Select.test.tsx
Fix merge error in Select tests
> **NOTE**  
=> Fix(Select): fix merge in Select.test.tsx

src/components/Modal/Modal.module.css
This PR has the goal of restoring the `bodyFullWidth` prop on the `Modal` component to make sure this mode is actually implemented in the default and with aside cases.
> **NOTE**  
Based on your changes, some of these checks may not apply. Please make sure to check the relevant items in …
=> fix(Modal): fixed bodyFullWidth behavior 

scripts/build-icons.ts
=> Fix(Icon): Added antd icons to build-icons script

src/components/Badge/Badge.module.css, src/components/Badge/Badge.props.ts, src/components/Badge/Badge.stories.tsx, src/components/Badge/Badge.test.tsx, src/components/Badge/Badge.tsx, src/components/Badge/__snapshots__/Badge.test.tsx.snap, src/components/Badge/index.ts, src/index.ts
This PR introduces the Badge component, which serves the purpose of highlighting a specific resource, emphasize some of its main features and group the most important associated actions.
The new component is designed to be contained inside a parent component, such as a `Card` component, and will take the entire width of the parent, while its height has been fixed to `80px`.
The component has two required properties:
```
icon: IconComponent
title: string | ReactNode
```
This is the complete list of properties:
```
type BadgeProps = {
description?: string | ReactNode;
extra?: ReactNode;
icon: IconComponent;
title: string | ReactNode;
titleExtra?: ReactNode;
}
```
> **NOTE**  
> Some labels are used to generate …
=> feat: add Badge component

src/components/BaseInput/props.ts, src/components/Checkbox/Checkbox.tsx, src/components/Checkbox/props.ts, src/components/Form/Form.stories.tsx, src/components/Input/Input.tsx, src/components/InputNumber/InputNumber.tsx, src/components/Search/Search.tsx, src/components/Select/Select.tsx, src/components/TextArea/TextArea.tsx
Added `autoFocus` prop to the component used as form fields
- added `autoFocus` prop
> **NOTE**  
=> fix(Form): Added autoFocus prop on the components used as form fields

src/assets/icons/icons.stories.mdx
=> fix unresolved icon

src/components/Form/props.ts
Change initialValues type: from Values to Partial<Values>
> **NOTE**  
=> Fix(Form): change initialValues prop type

src/components/CardSelection/CardSelection.module.css, src/components/Checkbox/checkbox.module.css, src/components/CheckboxGroup/CheckboxGroup.module.css, src/components/RadioGroup/RadioGroup.module.css, src/components/RadioGroup/components/Radio/index.module.css
Minor style fixes on checkbox and radio component
- Checkbox
- CheckboxGroup
- Radio
- RadioGroup
- SelectionCard
> **NOTE**  
=> Fix(Checkbox + Radio): Minor style fixes on checkbox and radio components

src/components/Tag/Tag.module.css
Tag component: Fixed color design-tokens
> **NOTE**  
=> fix(tag component): fixed color design-tokens

src/components/Tag/Tag.module.css
Fixed wrong design-tokens in Tag component
> **NOTE**  
=> fix(tag): fixed wrong design-tokens

src/components/Dropdown/Dropdown.tsx
- changed overflow value from "scroll" to "auto" to hide scrollbar
> **NOTE**  
=> change: overflow scroll with auto

src/components/Form/Form.tsx
- expose useFormInstance hooks
> **NOTE**  
=> added: export of useFormInstance hook

src/components/Table/Table.Action.tsx, src/components/Table/Table.stories.tsx, src/components/Table/Table.test.tsx, src/components/Table/Table.types.ts, src/components/Table/__snapshots__/Table.test.tsx.snap
=> feat(Table): support custom action button with label and primary layout

package.json, src/components/CodeEditor/CodeEditor.module.css, src/components/CodeEditor/CodeEditor.stories.tsx, src/components/CodeEditor/CodeEditor.test.tsx, src/components/CodeEditor/CodeEditor.tsx, src/components/CodeEditor/index.ts, src/components/CodeEditor/props.tsx, src/index.ts, yarn.lock
Add the new `CodeEditor` component
> **NOTE**  
=> feat: add code editor component
